### PR TITLE
Tree-sitter support

### PR DESCRIPTION
**Pull request by sadikovi**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Adds tree-sitter support for language-java. I added unit tests to cover the changes in tree-sitter grammar.
I had to link tree-sitter-dev (https://github.com/sadikovi/tree-sitter-java/) package that contains my patches. I will push them upstream later.

### Alternate Designs

Not applicable.

### Benefits

Adds support for tree-sitter, makes language highlighting more robust and fixes some of the old issues of regex highlighting.

### Possible Drawbacks

None, it does not affect TextMate grammar, also users can always disable tree-sitter support in the editor settings.

### Applicable Issues

N/A

### CODE REVIEW

**Comment by sadikovi** [comment]
There are a few issues with this PR, enums don't seem to be rendered correctly:
```
private enum ContainerState {
  /**
   * We haven't checked the container state yet.
   */
  Unknown,
  /**
   * We checked and the container doesn't exist.
   */
  DoesntExist,
  /**
   * The container exists and doesn't have an WASB version stamp on it.
   */
  ExistsNoVersion,
  /**
   * The container exists and has an unsupported WASB version stamped on it.
   */
  ExistsAtWrongVersion,
  /**
   * The container exists and has the proper WASB version stamped on it.
   */
  ExistsAtRightVersion
}
```

This code highlights the variable incorrectly:
```
class A {
  void func() {
    log.debug("debug");
    log.property.debug("debug");
  }
}
```

**Comment by sadikovi** [comment]
Also found that if statements are not collapsable.

**Comment by sadikovi** [comment]
This also does not highlight correctly:
```java
static {
  loadLibrary("libname");
}
```

**Comment by sadikovi** [comment]
I will get back to it ASAP.

**Comment by sadikovi** [comment]
There are still a few issues with tree-sitter-java that I would try addressing first:
1. `package_declaration` should not use `scoped_identifier`, and instead should be similar to `import_declaration`.
2. `class_literal` should not use `scoped_identifier`, and, instead, should be similar to `import_declaration`.
3. generics do not resolve correctly with a few examples.
4. difficult to extract method name in `method_invocation`.

**Comment by 50Wliu** [comment]
You need to change the Appveyor image to Visual Studio 2015.

**Comment by sadikovi** [comment]
Thanks @50Wliu! That fixed the problem! I should be able to merge tree-sitter support for Java!

**Comment by 50Wliu** [comment]
You should keep the package lock. It keeps installs consistent and also faster when using ci.

**Comment by sadikovi** [comment]
I reverted the last commit, thanks!

**Comment by sadikovi** [comment]
Add support for javadoc param, returns, throws, etc.

**Comment by 50Wliu** [comment]
Try replacing https://github.com/atom/language-java/blob/master/appveyor.yml with https://github.com/atom/ci/blob/master/appveyor.yml

**Comment by sadikovi** [comment]
@50Wliu Thanks. I updated the file to what you suggested previously - now it works. Travis still fails:
```
$ curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
The command "curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh" exited with 0.
0.00s$ chmod u+x build-package.sh
The command "chmod u+x build-package.sh" exited with 0.
$ ./build-package.sh
Downloading latest Atom release on the beta channel...
Using Atom version:
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

Do you know why atom beta build might be failing?

**Comment by 50Wliu** [comment]
I have no clue, sorry :(. I've been out of the loop for more than a year now.

**Comment by 50Wliu** [comment]
You could try updating from Trusty to Xenial or Bionic though and seeing if that helps.

**Comment by sadikovi** [comment]
I have tested this PR manually on our internal Java codebase as well, everything has worked so far.

**Comment by 50Wliu** [comment]
I no longer have the expertise to be comfortable with a sign-off, but I'd say I'd be pretty comfortable with you merging it :).

The only thing I would change is to depend on a non `-dev` package :).

**Comment by sadikovi** [comment]
dev package is a fork of tree-sitter with a few of my patches (https://github.com/sadikovi/tree-sitter-java/), which are required to get the grammar to work correctly. I am going to keep for now and push the changes upstream in meanwhile.

**Comment by sadikovi** [comment]
Thanks for the review @50Wliu. I am going to merge this PR, we can revert it if we find any issues this week.

**Pull request merged**
