### PR TITLE
Tokenize instance variables correctly

### PR DESCRIPTION
**Pull request by 50Wliu**
Fixes:
* comments not being recognized
* storage modifier not being identified as part of the variable declaration when using primitive types or `def`

Also changed the capture name from `meta.definition.variable.name.java` to `variable.definition.java`.

### CODE REVIEW

**Comment by noseglid** [comment]
Why are you removing the token on the name of the defined variable?

**Comment by 50Wliu** [comment]
I didn't remove it, I changed it from `meta.definition.variable.name` to `variable.definition` as `meta` isn't supposed to be used there.

**Comment by noseglid** [comment]
Ah, right you are. This looks good to me! 👍

**Comment by 50Wliu** [comment]
Thanks @noseglid!

**Pull request merged**
